### ISSUE TITLE
Add project license

### ISSUE THREAD

**Issue by mirjan-hoffmann** [swingbit/jira2gitlab#17]
Hi!

Many thanks for this project. In order to use the project in a legally compliant manner, a licence valid for the entire project is required. Could you please add a license? If ok for you, an open license like MIT or Apache License 2.0 would be helpful.

Best regards, Mirjan

**Comment by swingbit** [comment]
Hi @mirjan-hoffmann , good point, thanks for pointing that out. I just added it.
