### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 || Few Questions

### ISSUE THREAD

**Issue by ptbuchanan21** [swingbit/jira2gitlab#23]
Hello, I cloned your repo because I am trying to transfer my attachments and comments from Jira to GitLab, but I ran into json.decoder.JSONDecodeError: Expecting value: line 1 column 1.  

I imagine I have one of my credentials wrong, so I wanted to reach out and ask if I had something wrong in hopes of fixing the error:

1) Is the Jira URL supposed to be on the browse page, issue page or another Jira page?  Currently, the Jira URL I provide is the URL for one task under the browse page, I wasn't sure which URL to provide since it just says Jira URL.
2) Is the GitLab URL supposed to be on the 'Issues' page? Again, I wasn't sure which URL to provide since it just says GitLab URL.
3) For GitLab token, is this feed token or personal access token? I assume feed token, I don't think I had this wrong. Also have all the privileges. 
4) Is GITLAB_ADMIN supposed to just be left as just 'root'? I am an administrator for my project.
5) Do you know why I need to be a Jira administrator?
Thank you!

**Comment by ptbuchanan21** [comment]
Thank you very much for getting back to me with these responses!  I will go back and change the two URLs' since I may be overcomplicating them.  I will keep you updated on my progress.  Also, have you ever considered making a demo of the before and after of running your scripts?  I was just curious, since that could be insightful!  Thank you again.

**Comment by swingbit** [comment]
Good idea about the demo. To be honest I made this tool because I needed it in my company, and after I migrated everything we got rid of Jira for good, so I no longer have a Jira instance to test with. I could install one, but I need to find the time for that.

In any case, I recommend that you start safe. For my own migration, I first tested this thoroughly on a temporary Gitlab instance, destroying the imported projects and test the import over and over, until I was satisfied. Only then I ran the import on the real Girlab instance.

**Comment by ptbuchanan21** [comment]
I completely understand.  I will also do that, I am working on testing and adding one issue at a time rather than moving everything.  I also made my own repo and Jira to test before using the real project.  

I also went back to work the URLs since I may be overcomplicating this; would this Jira link be the /summary page for the project I am apart of?  Or would it be the system dashboard page when clicking on the main logo?  I have the same question for GitLab, would I include the group I am apart of or just the GitLab link that displays when clicking on the icon?  I wasn't sure if I should include the URL when viewing the issues and projects, or just the overarching URL.  I also will leave in 'root' since I am the administrator for the repo.  Thank you again for getting back too me, I genuinely appreciate the feedback and this work.  I am also trying to move over our Jira tasks to GitLab for my team!

**Comment by swingbit** [comment]
Those URLs should really be the base URLs of the application, in both Jira and Gitlab. No project, no issue, no summary, no dashboard page. Most likely, you shouldn't have a single `/` in there.

**Comment by ptbuchanan21** [comment]
Got it, thank you! Getting an error now saying (requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url) I am going to keep playing around until I fix it.  Thank you again for helping me.

**Comment by ptbuchanan21** [comment]
Hi @swingbit, I had one more question for you since I've been trying to fix my 401 error.  For the GitLab token, do you know which token I should use; as in personal access token, group token, project token?  Thank you!

**Comment by swingbit** [comment]
I recommend a personal token from an Administrator, with full rights. This migration is meant to be an Administrator job, which fiddles not only with project issues but also with global entities such as users.

**Comment by ptbuchanan21** [comment]
I understand thank you.  I also had one more technical related question for you but I will create a separate issue so you see it.
