### ISSUE TITLE
replacements = move_attachments(issue['fields']['attachment'], gitlab_project_id) KeyError: 'attachment'

### ISSUE THREAD

**Issue by ptbuchanan21** [swingbit/jira2gitlab#24]

**Comment by ptbuchanan21** [comment]
File "./jira2gitlab.py", line 959, in <module>
    migrate_project(jira_project, gitlab_project)
  File "./jira2gitlab.py", line 567, in migrate_project
    replacements = move_attachments(issue['fields']['attachment'], gitlab_project_id)
KeyError: 'attachment'


I am getting this error on line 567.  Do you know why it would be breaking here?  My project does have attachments, reading into Jira's API if something had changed.

**Comment by swingbit** [comment]
I'm not sure why this would happen. I've migrated hundreds of thousands of issues from Jira, and the field always existed, no matter whether attachments were there or not.

In any case, I added a guard. It can't hurt and hopefully solves the issue.

**Comment by ptbuchanan21** [comment]
That fixed the issue, getting a 403 error but I most likely will be able to sort through that. Anyways, thank you for that addition!
