### ISSUE TITLE
KeyError: 'Modernize FrontEnd' || custom field error

### ISSUE THREAD

**Issue by ptbuchanan21** [swingbit/jira2gitlab#25]
Hi @swingbit, I'd first like to say I appreciate all the help you've given to me as I use your script.  My issues are migrating over **successfully** and this will benefit my team a lot.  I had one error that came up that I thought I'd ask you about though.  I am getting this after my issues are being created, any ideas on what I can do to resolve this: 

**Traceback (most recent call last):
  File "./jira2gitlab.py", line 962, in <module>
    migrate_project(jira_project, gitlab_project)
  File "./jira2gitlab.py", line 654, in migrate_project
    if issue['fields'][key]:
KeyError: 'Modernize FrontEnd'**

I created this custom field in the config file under my Epic Field, then have it in Jira Custom Fields with Metadata 1, trying to figure out what I'm doing wrong.  I don't see my attachments either, but I feel like this could be related.  Anyways, thank you for your awesome project.

https://github.com/swingbit/jira2gitlab/blob/d417b1e3fc4bba6be0c55c2fa470976cd71bebd0/jira2gitlab.py#L653

**Comment by swingbit** [comment]
To be honest the custom fields were someone else's contribution and I've never tested them. I just saw that the code assumed all issues had the given custom fields. I just added a guard, to first check if the custom field is indeed available,.

**Comment by ptbuchanan21** [comment]
I understand, do you know which contributor made the custom fields?  If not, it's totally ok I was just going to ask what the Metadata would look like in the JIRA_CUSTOM_FIELD dictionary.

**Comment by swingbit** [comment]
Looking again at the error, it seems to me that you may have swapped the key and value in 
```
JIRA_CUSTOM_FIELDS = {
    'customfield_14200': 'Metadata 1',
    'customfield_14201': 'Metadata 2',
}
```

The key (1st field) must be the name of the custom field, not a text label like "Modernize FrontEnd". I expect something like `customfield_12345`.

**Comment by ptbuchanan21** [comment]
I was able to fix this issue, thank you.  Before I close this issue, do you know if there are custom labels?

**Comment by swingbit** [comment]
If you mean whether you can have the same mapping by using labels instead of field names, then no you can't.

**Comment by ptbuchanan21** [comment]
Got it, thank you.
