### ISSUE TITLE
Request participants

### ISSUE THREAD

**Issue by xenago** [swingbit/jira2gitlab#5]
Great work, thank you for sharing it!

Maybe I missed something but Request participants doesn't seem to be supported currently in the script.

This feature is not exactly equivalent on GitLab, but the /cc @username feature is probably the closest thing:
https://gitlab.com/gitlab-org/gitlab/-/issues/197288

Any thoughts about this? Either appending the cc's to the bottom of the description or adding as a comment might work, though I haven't looked at the traffic yet to see exactly what is happening when I CC a user.

Cheers!

**Comment by swingbit** [comment]
Hi @xenago , thanks for your input.

As far as I understand, the Participants field is a feature of Jira Service Desk, and it is not available in Jira Software (https://community.atlassian.com/t5/Jira-questions/Adding-quot-Request-Participants-quot-in-Jira-Software/qaq-p/595627)

However this reminds me that I have not migrated the Watchers field, which is indeed most similar to `/cc` in Gitlab.

**Comment by xenago** [comment]
No worries, thanks for the info! The watchers field will be very useful in any case.
