### ISSUE TITLE
User(s) with existing admin rights incorrectly set to non-admin after import

### ISSUE THREAD

**Issue by caseybea** [swingbit/jira2gitlab#7]
The script as written (when allowed to) temporarily grants admin rights to users so that timestamps can be set properly.   Clearly needed, and a cool way to handle this.

Unfortunately, the script does not check for what rights the user HAD prior to the import.   If a user had admin rights beforehand, that user is incorrectly reset to non--admin when the script finishes.

**Comment by swingbit** [comment]
@caseybea could you please test the change above?

**Comment by caseybea** [comment]
Yes will test the new code immediately.

**Comment by caseybea** [comment]
Whoops!      So, unfortunately the patch/fix did not work; and in fact ended up leaving everyone that didn't have admin rights with the admin rights....  so now when the export/import fiished, instead of adding admin rights back to a small number of people, I had to go in and REMOVE admin rights from a much larger population :-(

Screen log from the export below showing the issue with the admin rights.  It errors out trying to reset the users.
=====================================
Resetting user privileges..

- User kthorat was made admin during the import to set the correct timestamps. Turning it ba                                                                                                        ck to non-admin.
- User jsmith was made admin during the import to set the correct timestamps. Turning it bac                                                                                                        k to non-admin.
- User motutaj was made admin during the import to set the correct timestamps. Turning it ba                                                                                                        ck to non-admin.
- User stsaih was made admin during the import to set the correct timestamps. Turning it bac                                                                                                        k to non-admin.
- User mtutaj was made admin during the import to set the correct timestamps. Turning it bac                                                                                                        k to non-admin.
- User kosinski was made admin during the import to set the correct timestamps. Turning it b                                                                                                        ack to non-admin.
- User rswanson was made admin during the import to set the correct timestamps. Turning it b                                                                                                        ack to non-admin.
- User wdemos was made admin during the import to set the correct timestamps. Turning it bac                                                                                                        k to non-admin.
- User kawoods was made admin during the import to set the correct timestamps. Turning it ba                                                                                                        ck to non-admin.
- User szacher was made admin during the import to set the correct timestamps. Turning it ba                                                                                                        ck to non-admin.
- User llamers was made admin during the import to set the correct timestamps. Turning it ba                                                                                                        ck to non-admin.
- User dabell was made admin during the import to set the correct timestamps. Turning it bac                                                                                                        k to non-admin.
- User bskrade was made admin during the import to set the correct timestamps. Turning it ba                                                                                                        ck to non-admin.
- User jdepons was made admin during the import to set the correct timestamps. Turning it ba                                                                                                        ck to non-admin.
- User mastake was made admin during the import to set the correct timestamps. Turning it ba                                                                                                        ck to non-admin.
- User wjin was made admin during the import to set the correct timestamps. Turning it back                                                                                                         to non-admin.
- User moium was made admin during the import to set the correct timestamps. Turning it back                                                                                                         to non-admin.
- User jthota was made admin during the import to set the correct timestamps. Turning it bac                                                                                                        k to non-admin.
- User kormoua was made admin during the import to set the correct timestamps. Turning it ba                                                                                                        ck to non-admin.

[ERROR] Could not reset priviledges:

An error occurred while reverting the admin status of Gitlab users.
IMPORTANT: The following users should be revoked the admin status manually:
[
    "moium",
    "kawoods",
    "llamers",
    "dabell",
    "bskrade",
    "kthorat",
    "mastake",
    "wjin",
    "motutaj",
    "kosinski",
    "rswanson",
    "mtutaj",
    "jthota",
    "wdemos",
    "kormoua"
]

[root@butler jira2gitlab-main]#

**Comment by swingbit** [comment]
ouch, sorry about that. Perhaps I did something wrong with the last commit. Checking.

**Comment by swingbit** [comment]
I reverted the last commit. I think it should work now. Sorry but I don't have a test environment up, at the moment.

To test this, you can interrupt the script after a few minutes and check if it behaved correctly regarding the users.

**Comment by caseybea** [comment]
OK will try.

**Comment by caseybea** [comment]
Nope.   totally new error.   (we're ok here, I am willing to help keep trying!).    Note I am wiping out my issues and starting with a blank project every time and also nuking the pickle file.

[INFO] #1/2304 Migrating Jira issue ITS-1 ...   Traceback (most recent call last):
  File "./jira2gitlab.py", line 886, in <module>
    migrate_project(jira_project, gitlab_project)
  File "./jira2gitlab.py", line 453, in migrate_project
    gl_assignee = [resolve_login(issue['fields']['assignee']['name'])['id']]
  File "./jira2gitlab.py", line 281, in resolve_login
    return gl_user
UnboundLocalError: local variable 'gl_user' referenced before assignment


Migration failed


Resetting user privileges..

**Comment by swingbit** [comment]
Of course. I hope it's fixed now.

**Comment by caseybea** [comment]
Sorry for the delay- boss had me on something else for a bit.

Confirmed- the fial fix did the trick!   Thank you.
